In [1]:
import pandas as pd
import numpy as np

In [28]:
sal = pd.read_csv("Salaries.csv", error_bad_lines=False)

/home/priyankat/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [29]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

  BasePay OvertimePay OtherPay Benefits   TotalPay  TotalPayBenefits  Year  \
0  167411           0   400184      NaN  567595.43         567595.43  2011   
1  155966      245132   137811      NaN  538909.28         538909.28  2011   
2  212739      106088  16452.6      NaN  335279.91         335279.91  2011   
3   77916     56120.7   198307      NaN  332343.61         332343.61  2011   
4  134402        9737   182235      NaN  326373.19         326373.19  2011   

   Notes         Agency Status  
0    NaN  San Francisco    NaN  
1    NaN  San Francisco    NaN  
2    NaN  San Francisco    NaN  
3    NaN  San Francisco    NaN  
4    NaN  San Francisco    NaN

In [30]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
Id                  148654 non-null int64
EmployeeName        148654 non-null object
JobTitle            148654 non-null object
BasePay             148049 non-null object
OvertimePay         148654 non-null object
OtherPay            148654 non-null object
Benefits            112495 non-null object
TotalPay            148654 non-null float64
TotalPayBenefits    148654 non-null float64
Year                148654 non-null int64
Notes               0 non-null float64
Agency              148654 non-null object
Status              38119 non-null object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB


In [38]:
sal['BasePay'].values==np.float

array([False, False, False, ..., False, False, False])

In [43]:
sal_num = sal[pd.to_numeric(sal.BasePay, errors='coerce').notnull()]

In [45]:
sal_num.BasePay.values

array([167411.18, 155966.02, 212739.13, ..., '0.00', '0.00', '0.00'],
      dtype=object)

In [52]:
sal_num1 = sal_num[sal_num['BasePay'].apply(lambda x: isinstance(x,float))]

In [53]:
sal_num1.BasePay.values

array([167411.18, 155966.02, 212739.13, ..., 65055.0, 65054.68, 60135.15],
      dtype=object)

In [54]:
sal_num1.BasePay.mean()

71323.83957370375

In [60]:
sal_num2 = sal_num[sal_num['OvertimePay'].apply(lambda x: isinstance(x, float))]
sal_num2.OvertimePay.values

array([0.0, 245131.88, 106088.18, ..., 0.0, 0.0, 2630.34], dtype=object)

In [61]:
sal_num2.OtherPay.max()

400184.25

In [70]:
sal.loc[sal.EmployeeName == 'JOSEPH DRISCOLL', 'JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [71]:
sal.loc[sal.EmployeeName == 'JOSEPH DRISCOLL', 'TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [83]:
sal.loc[sal.TotalPayBenefits == sal.TotalPayBenefits.max()]

Id    EmployeeName                                        JobTitle BasePay  \
0   1  NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411   

  OvertimePay OtherPay Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
0           0   400184      NaN  567595.43         567595.43  2011    NaN   

          Agency Status  
0  San Francisco    NaN

In [84]:
sal[sal.TotalPayBenefits == sal.TotalPayBenefits.min()]

Id EmployeeName                    JobTitle BasePay OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch    0.00        0.00   

       OtherPay Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653  -618.13     0.00   -618.13           -618.13  2014    NaN   

               Agency Status  
148653  San Francisco     PT

In [100]:
years = sal.Year.unique()
years

array([2011, 2012, 2013, 2014])

In [94]:
sal[sal.Year==2014]['BasePay'].values

array([129150.01, 318835.49, 257340.0, ..., 'Not Provided',
       'Not Provided', '0.00'], dtype=object)

In [113]:
sal_num3 = sal_num[sal_num['BasePay'].apply(lambda x: isinstance(x, float))]
sal_num3[sal_num3.Year == 2014]['BasePay'].mean()


98516.40637796959

In [107]:
for i in years:
    print(i ," ",sal_num3[sal_num3.Year ==  i]['BasePay'].mean())

2011   63595.956516774524
2012   65436.40685742255
2013   69630.0302164812
2014   98516.40637796959


In [112]:
sal.groupby('Year').mean()

Id      TotalPay  TotalPayBenefits  Notes
Year                                                 
2011   18080.0  71744.103871      71744.103871    NaN
2012   54542.5  74113.262265     100553.229232    NaN
2013   91728.5  77611.443142     101440.519714    NaN
2014  129593.0  75463.918140     100250.918884    NaN

In [122]:
sal.JobTitle.nunique()

2159

In [125]:
sal.JobTitle.value_counts().head()

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [129]:
sum(sal[sal.Year == 2013]['JobTitle'].value_counts()==1)

202

In [139]:
sum(sal[sal.JobTitle.str.contains('Chief')]['JobTitle'].value_counts())

423

In [142]:
sal['title_len']=sal.JobTitle.apply(len)

In [146]:
sal[['JobTitle', 'title_len']].corr()

title_len
title_len        1.0

In [148]:
sal[['title_len', 'TotalPayBenefits']].corr()

title_len  TotalPayBenefits
title_len          1.000000         -0.036878
TotalPayBenefits  -0.036878          1.000000